apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deployment
  namespace: teoschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
        - name: hasher
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/crdjiby:hasher-v1.2.0
          resources:
            requests:
              memory: "30Mi"
              cpu: "0.1"
            limits:
              memory: "40Mi"
              cpu: "0.2"
          ports:
            - containerPort: 80
