name: Build and Push Image Hasher

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Push Docker Image
        run: |
          cd ./micro-services/hasher
          IMAGE_NAME=img_hasher
          IMAGE_TAG=v1.0.0
          ECR_NAME=crdjiby
          # Use the AWS_ACCOUNT_ID secret variable
          ECR_LOGIN_SERVER=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com

          # Build the Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

          # Tag the Docker image
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_LOGIN_SERVER/$ECR_NAME:$IMAGE_NAME-$IMAGE_TAG

          # Login to ECR
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin $ECR_LOGIN_SERVER

          # Push the Docker image to ECR
          docker push $ECR_LOGIN_SERVER/$ECR_NAME:$IMAGE_NAME-$IMAGE_TAG