name: Destroy resources AWS

on:
  workflow_dispatch

jobs:
  cloudformation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./TeoSchool 
        run: terraform init -reconfigure

      - name: Destroy if approved
        working-directory: ./TeoSchool
        run: terraform destroy -auto-approve
