name: Delete resources EKS

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Get credentials
        run: aws eks --region ${AWS_REGION} update-kubeconfig --name djiby-eks-cluster
        
      - name: Delete Deployments
        run: |
          cd ./k8s
          kubectl delete deployment hasher-deployment -n teoschool
          kubectl delete deployment redis-deployment -n teoschool
          kubectl delete deployment rng-deployment -n teoschool
          kubectl delete deployment webui-deployment -n teoschool
          kubectl delete deployment worker-deployment -n teoschool

      - name: Delete Services
        run: |
          cd ./k8s
          kubectl delete service hasher -n teoschool
          kubectl delete service redis -n teoschool
          kubectl delete service rng -n teoschool
          kubectl delete service webui -n teoschool
      
      - name: Delete namespace
        run: |
          cd ./k8s
          kubectl delete namespace teoschool
