name: Deploy Prometheus and Grafana on AKS

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check and Install AWS CLI
        run: |
            if ! command -v aws &> /dev/null
            then
              echo "AWS CLI not found. Installing..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
            fi
        shell: bash

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get credentials
        run: aws eks --region ${AWS_REGION} update-kubeconfig --name djiby-eks-cluster

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
        shell: bash

      - name: Create a namespace for Prometheus and Grafana
        run: kubectl create ns prometheus

      - name: Install Prometheus and Grafana using Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus

      #- name: Port-forward Prometheus
      #  run: kubectl port-forward -n prometheus svc/prometheus-prometheus-operated 9090:9090

      #- name: Port-forward Grafana
      #  run: kubectl port-forward -n prometheus svc/prometheus-grafana 3000:80 &